import type { Metadata } from "next";
import { Open_Sans, Noto_Sans, Roboto } from "next/font/google";
import "./globals.css";

const font = Open_Sans({ subsets: ["latin"] });

import { getGlobalData } from "@/data/loaders";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalData();
  return (
    <html lang="en">
      <body className={`${font.className} bg-[#fffff]`}>
        <Header data={globalData.header} />
        <div>{children}</div>
        <Footer data={globalData.footer} />
      </body>
    </html>
  );
}
